spring:
  # Database ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
  # JPA ??
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      #format_sql: true
      #show_sql: false
      #use_sql_comments: true
    open-in-view: false
  jwt:
    secret-key: ${spring.jwt.secret-key}

    access:
      expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
      header: Authorization

    refresh:
      expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
      header: Authorization-refresh

  security:
    oauth2:
      client:
        registration:
          #          google:
          #            client-id: 구글 클라이언트 ID
          #            client-secret: 구글 클라이언트 Secret
          #            scope: profile, email
          #
          #          naver:
          #            client-id: 네이버 클라이언트 ID
          #            client-secret: 네이버 클라이언트 Secret
          #            redirect-uri: http://localhost:8080/login/oauth2/code/naver (설정한 redirect URI)
          #            authorization-grant-type: authorization_code
          #            scope: name, email, profile_image
          #            client-name: Naver

          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            redirect-uri: ${kakao.redirect-uri}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id